-- CEJ Database bootstrap / sync script for Supabase
-- Safe to run multiple times (uses IF NOT EXISTS where possible)

-- ============================================================
-- 1. INITIAL CONFIGURATION
-- ============================================================

-- Enable UUID extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- ============================================================
-- 2. GENERIC FUNCTION: updated_at
-- ============================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS     trigger
LANGUAGE    plpgsql
SET         search_path = pg_catalog, public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


-- ============================================================
-- 3. TABLE: PROFILES (Auth Extension - Phase 3)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.profiles (
  id           uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email        text,
  full_name    text,
  phone        text,
  company_name text,
  rfc          text,
  address      jsonb,
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now()
);

-- Enable Row Level Security for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Clean up existing policies to avoid duplicates
DROP POLICY IF EXISTS "Users can read their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Usuarios ven su propio perfil" ON public.profiles;
DROP POLICY IF EXISTS "Usuarios editan su propio perfil" ON public.profiles;

-- RLS: Users can only read their own profile
CREATE POLICY "Users can read their own profile"
  ON public.profiles FOR SELECT
  USING (id = (SELECT auth.uid()));

-- RLS: Users can only update their own profile
CREATE POLICY "Users can update their own profile"
  ON public.profiles FOR UPDATE
  USING (id = (SELECT auth.uid()));

-- updated_at trigger for profiles
DROP TRIGGER IF EXISTS set_profiles_updated_at ON public.profiles;
CREATE TRIGGER set_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE PROCEDURE public.set_updated_at();

-- Trigger: automatically create profile for new auth users (with COALESCE fallback)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (
    NEW.id,
    NEW.email,
    -- Use metadata full_name if present, otherwise fallback to email local-part
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1))
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- ============================================================
-- 4. TABLE: LEADS (Anonymous Inbox - Phase 2)
-- ============================================================

-- Base definition for new environments
CREATE TABLE IF NOT EXISTS public.leads (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz DEFAULT now(),
  name        text NOT NULL,
  phone       text NOT NULL,
  status      text DEFAULT 'new',
  quote_data  jsonb NOT NULL,
  visitor_id  text,
  fb_event_id text,
  utm_source  text,
  utm_medium  text
);

-- MIGRATION / SYNC FOR EXISTING DATABASES:
-- Add missing columns without changing existing values.
ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS fbclid              text,
  ADD COLUMN IF NOT EXISTS delivery_date       timestamptz,
  ADD COLUMN IF NOT EXISTS delivery_address    text,
  ADD COLUMN IF NOT EXISTS utm_campaign        text,
  ADD COLUMN IF NOT EXISTS utm_term            text,
  ADD COLUMN IF NOT EXISTS utm_content         text,
  ADD COLUMN IF NOT EXISTS notes               text,
  ADD COLUMN IF NOT EXISTS lost_reason         text,
  ADD COLUMN IF NOT EXISTS privacy_accepted    boolean,
  ADD COLUMN IF NOT EXISTS privacy_accepted_at timestamptz;

-- Ensure new records default to false,
-- while historical rows remain NULL (unknown).
ALTER TABLE public.leads
  ALTER COLUMN privacy_accepted SET DEFAULT false;

-- OPTIONAL (run separately if quote_data is still text in production):
-- This makes sure quote_data is jsonb everywhere.
-- ALTER TABLE public.leads
--   ALTER COLUMN quote_data TYPE jsonb
--   USING quote_data::jsonb;

-- Enable Row Level Security for leads
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
-- Note: no public INSERT policy on leads; inserts are done via Server Actions
-- using the Supabase Service Role, which bypasses RLS.


-- ============================================================
-- 5. TABLE: ORDERS (SaaS Orders & History - Phase 4)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.orders (
  id               uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id          uuid REFERENCES public.profiles(id) NOT NULL,
  folio            text NOT NULL,                    -- Human-friendly ID (e.g. WEB-2025-001)
  status           text DEFAULT 'draft',             -- 'draft', 'pending_payment', 'scheduled', 'delivered', 'cancelled'
  total_amount     numeric(10,2) NOT NULL,
  currency         text DEFAULT 'MXN',
  items            jsonb NOT NULL DEFAULT '[]'::jsonb, -- [{ id, label, inputs, results }]
  delivery_date    timestamptz,
  delivery_address text,
  geo_location     jsonb,                            -- { lat, lng }
  created_at       timestamptz DEFAULT now(),
  updated_at       timestamptz DEFAULT now()
);

-- Enable Row Level Security for orders
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Clean up existing policies to avoid duplicates
DROP POLICY IF EXISTS "Users can read their own orders" ON public.orders;
DROP POLICY IF EXISTS "Users can create their own orders" ON public.orders;
DROP POLICY IF EXISTS "Users can update their draft orders" ON public.orders;
DROP POLICY IF EXISTS "Usuarios ven sus propias ordenes" ON public.orders;
DROP POLICY IF EXISTS "Usuarios crean sus propias ordenes" ON public.orders;
DROP POLICY IF EXISTS "Usuarios actualizan sus ordenes (draft)" ON public.orders;

-- RLS: Users can only read their own orders
CREATE POLICY "Users can read their own orders"
  ON public.orders FOR SELECT
  USING (user_id = (SELECT auth.uid()));

-- RLS: Users can only create orders for themselves
CREATE POLICY "Users can create their own orders"
  ON public.orders FOR INSERT
  WITH CHECK (user_id = (SELECT auth.uid()));

-- RLS: Users can only update their own draft orders
CREATE POLICY "Users can update their draft orders"
  ON public.orders FOR UPDATE
  USING (user_id = (SELECT auth.uid()) AND status = 'draft');

-- updated_at trigger for orders
DROP TRIGGER IF EXISTS set_orders_updated_at ON public.orders;
CREATE TRIGGER set_orders_updated_at
  BEFORE UPDATE ON public.orders
  FOR EACH ROW
  EXECUTE PROCEDURE public.set_updated_at();


-- ============================================================
-- 6. TABLE: PRICE_CONFIG (Pricing Configuration - Phase 5)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.price_config (
  key         text PRIMARY KEY,          -- e.g. 'concrete_250_direct', 'pump_service_base'
  price_cents integer NOT NULL,          -- e.g. 150000
  currency    text DEFAULT 'MXN',        -- e.g. 'MXN'
  description text,                      -- e.g. 'Concrete 250kg direct delivery'
  active      boolean DEFAULT true,      -- e.g. true
  updated_at  timestamptz DEFAULT now()
);

-- Enable Row Level Security for price_config
ALTER TABLE public.price_config ENABLE ROW LEVEL SECURITY;

-- Clean up existing policies to avoid duplicates
DROP POLICY IF EXISTS "Public read access to prices" ON public.price_config;
DROP POLICY IF EXISTS "Lectura publica de precios" ON public.price_config;

-- RLS: public read-only access (write access will be added later for admins)
CREATE POLICY "Public read access to prices"
  ON public.price_config FOR SELECT
  USING (true);


-- ============================================================
-- 7. INDEXES (Performance Optimization)
-- ============================================================

-- LEADS
-- Remove legacy duplicate indexes if they exist (to avoid duplicate_index warnings)
DROP INDEX IF EXISTS leads_status_idx;
DROP INDEX IF EXISTS leads_visitor_id_idx;

-- Identify returning visitors
CREATE INDEX IF NOT EXISTS idx_leads_visitor_id ON public.leads(visitor_id);

-- Search by phone (basic CRM / deduplication)
CREATE INDEX IF NOT EXISTS idx_leads_phone ON public.leads(phone);

-- Filter/sort by creation date (dashboards, reporting)
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON public.leads(created_at);

-- Filter by pipeline status (new/contacted/converted/archived)
CREATE INDEX IF NOT EXISTS idx_leads_status ON public.leads(status);

-- Deep search inside quote_data JSON (e.g. by folio inside JSON)
CREATE INDEX IF NOT EXISTS idx_leads_quote_gin
  ON public.leads USING gin (quote_data);

-- ORDERS
-- Fast lookup of user order history
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
