import { z } from 'zod';

export const adminOrderPayloadSchema = z.object({
    name: z.string().trim().min(2, 'El nombre es obligatorio.'),
    phone: z.string().trim().min(10, 'El teléfono debe tener al menos 10 dígitos.'),
    forceNewCustomer: z.boolean().optional(),
    volume: z.number().positive('El volumen debe ser mayor a 0.'),
    concreteType: z.enum(['direct', 'pumped']),
    strength: z.string().trim().min(1, 'La resistencia es obligatoria.'),
    deliveryAddress: z.string().trim().min(5, 'La dirección de entrega es obligatoria.'),
    sellerId: z.string().uuid('El vendedor seleccionado no es válido.').optional(),
    orderedAt: z.string().datetime().optional(),
    deliveryDate: z.string().trim().optional(),
    scheduledSlotCode: z.string().trim().max(16).optional(),
    externalRef: z.string().trim().max(128).optional(),
    legacyFolioRaw: z.string().trim().max(128).optional(),
    notes: z.string().trim().optional(),
    utm_source: z.string().optional(),
    utm_medium: z.string().optional(),
    utm_campaign: z.string().optional(),
    utm_term: z.string().optional(),
    utm_content: z.string().optional(),
    fbclid: z.string().optional(),
    gclid: z.string().optional(),
});
